# Generated by Django 4.1.5 on 2023-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_helper', '0003_remove_binance_profile_margintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binance_profile',
            name='total_wallet_balance',
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='BNB_wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='BTC_wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='BUSD_wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='ETH_wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='USDC_wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='binance_profile',
            name='USDT_wallet',
            field=models.FloatField(default=0),
        ),
    ]
