services:

  django:
    volumes:
      - .:/src/:rw
      - statics:/src/static:rw
    env_file:
      - ./config/gunicorn.dev.env
      - ./config/django.dev.env
      - ./config/postgres.dev.env
    entrypoint: [ "bash", "./entrypoint.dev.sh" ]

  postgres:
    env_file:
      - ./config/postgres.dev.env
    volumes:
      - db-data-test:/var/lib/postgresql/data:rw

  nginx:
    depends_on:
      - django
    env_file:
      - ./config/gunicorn.dev.env
    ports:
      - 8000:80
    volumes:
      - statics:/statics:rw

  celery_worker:
    env_file:
      - ./config/django.dev.env
      - ./config/postgres.dev.env
    command: celery -A kucoin_updater.tasks worker --loglevel=info  

  
  celery_beat:
    env_file:
      - ./config/django.dev.env
      - ./config/postgres.dev.env
    command: celery -A kucoin_updater.beat beat --loglevel=info

volumes:
  db-data-test:
  statics: