# Generated by Django 4.2.7 on 2023-12-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('side', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('remark', models.CharField(max_length=128)),
                ('stp', models.CharField(max_length=128)),
                ('trade_type', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
