# Generated by Django 4.0.6 on 2022-07-21 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_profile_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('opType', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('fee', models.CharField(max_length=20)),
                ('isActive', models.CharField(max_length=20)),
                ('order_createdAt', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveTrackingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
