# Generated by Django 4.2 on 2023-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='mark_price',
            field=models.FloatField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='mark_value',
            field=models.FloatField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='rist_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.CharField(default='XBTUSDM', max_length=10),
        ),
    ]
