# Generated by Django 4.2 on 2023-04-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_position_mark_price_position_mark_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='rist_limit',
            new_name='risk_limit',
        ),
    ]
