# Generated by Django 4.2 on 2023-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kucoin_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kucoin_api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
