# Generated by Django 4.2 on 2023-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_kucoin_api_key_user_kucoin_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kucoin_passphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
