# Generated by Django 3.2.8 on 2022-07-22 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=65, unique=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Name')),
                ('security_passphrase', models.CharField(max_length=100, verbose_name='Security Pass phrase')),
                ('kc_pp', models.CharField(max_length=40, verbose_name='Kucoin Pass Phrase')),
                ('kc_apikey', models.CharField(max_length=100, verbose_name='Kucoin Api Key')),
                ('kc_secret', models.CharField(max_length=255, verbose_name='Kucoin Secret')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('date_joined',),
            },
        ),
    ]
