# Generated by Django 3.2.8 on 2022-07-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220724_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_update_orders',
            field=models.BooleanField(default=True, verbose_name='Enable Auto Update Orders'),
        ),
    ]
