# Generated by Django 3.2.8 on 2022-07-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_auto_update_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kc_apikey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kucoin Api Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kc_pp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kucoin Pass Phrase'),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_passphrase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Security Pass phrase'),
        ),
    ]
