# Generated by Django 4.1.1 on 2022-09-23 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=64, null=True, verbose_name='symbol')),
                ('autoDeposit', models.BooleanField(default=False, verbose_name='auto deposit ?')),
                ('isOpen', models.BooleanField(default=False, verbose_name='is open ?')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
