# Generated by Django 4.1.1 on 2022-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='user name')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='name')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('kucoin_pass_pharese', models.CharField(max_length=256, verbose_name='pass phrase')),
                ('kucoin_api_key', models.CharField(max_length=256, verbose_name='api key')),
                ('kucoin_api_secret', models.CharField(max_length=256, verbose_name='api secret')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
