# Generated by Django 4.1.5 on 2023-01-16 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientOid', models.CharField(max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('tradeType', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
