# Generated by Django 4.1.5 on 2023-01-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_handler', '0002_remove_order_clientoid_position_binance_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binance_profile',
            name='marginType',
        ),
    ]
