# Generated by Django 4.1.5 on 2023-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_handler', '0004_remove_binance_profile_total_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binance_profile',
            name='total_wallet',
            field=models.FloatField(default=0),
        ),
    ]
