# Generated by Django 4.1.5 on 2023-01-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_handler', '0007_binance_profile_total_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binance_profile',
            name='total_wallet',
            field=models.FloatField(null=0),
        ),
    ]
