# Generated by Django 4.1.5 on 2023-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_handler', '0009_remove_binance_profile_total_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='leverage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='unRealizedProfit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
    ]
