# Generated by Django 4.2.1 on 2023-05-15 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=512)),
                ('currency', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=6)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('available', models.DecimalField(decimal_places=6, max_digits=20)),
                ('holds', models.DecimalField(decimal_places=6, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
