# Generated by Django 4.2.1 on 2023-05-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_field',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
